## workflow build config

# id and name for the workflow (bundle id = domain.id)
id: alfred-screenshot-ocr-workflow

# base domain
domain: com.tumblr.ramiroaraujo

name: Screenshot to Text
description: A Screenshot OCR reader to rapidly scan parts of the screen and capture the content to the clipboard.
created_by: Ramiro Araujo
website: https://github.com/ramiroaraujo/alfred-screenshot-ocr-workflow
readme: readme

## development config

# path is the relative path to the workflow in the project root
path: workflow

# If you are using Alfred's advanced Dropbox sync, indicate the path shown in
# Alfred Preferences > Advanced > Syncing:
dropbox: ~/Dropbox